version: '3'
services:
  data-server:
    build:
      context: .
      args:
        BINARY: data-server
        CONFIG: ./docker
      dockerfile: ./docker/Dockerfile.data-server
    hostname: data-server
    entrypoint: ["/bin/bash", "-cx", "/app/sqlx database create; /app/sqlx migrate run; /app/data-server"]
    depends_on:
      - redis
      - database
    stdin_open: true
    tty: true
    user: signatrust
    environment:
      RUST_LOG: $RUST_LOG
      DATABASE_URL: $DATABASE_URL
    ports:
      - "8088:8088"

  control-server:
    build:
      context: .
      args:
        BINARY: control-server
        CONFIG: ./docker
      dockerfile: ./docker/Dockerfile.data-server
    hostname: control-server
    depends_on:
      - redis
      - database
      - data-server
    stdin_open: true
    tty: true
    user: signatrust
    environment:
      RUST_LOG: $RUST_LOG
    entrypoint: ["/bin/bash", "-cx", "sleep 5; /app/control-server"]
    ports:
      - "8080:8080"

  redis:
    image: openeuler/redis:6.2.7-22.03-lts
    hostname: redis
    stdin_open: true
    tty: true
    volumes:
      - redis:/var/lib/redis/data
    command: redis-server --requirepass $REDIS_PASSWD
    ports:
      - "6379:6379"

  database:
    image: mysql:8.0
    hostname: database
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"

volumes:
  database:
  redis:
