apiVersion: v1
kind: ConfigMap
metadata:
  name: signatrust-config
data:
  client.toml: |
    working_dir = "/app/data/"
    worker_threads = 8
    buffer_size = 20480
    # consider the memory consumption if number bumped since all binaries will be stored in memory
    max_concurrency = 100
    [server]
    domain_name = "signatrust.test.osinfra.cn"
    tls_cert = ""
    tls_key = ""
    type = "dns"
    server_address = "signatrust-server-headless.signatrust-local-development.svc.cluster.local"
    server_port = "8088"
  server.toml: |
    name = "application"
    tls_cert = ""
    tls_key = ""
    ca_root = ""
    [data-server]
    server_ip = "0.0.0.0"
    server_port = "8088"
    [control-server]
    server_ip = "0.0.0.0"
    server_port = "8080"
    cookie_key = "2B5AEC57F7CC4FF8B4120AA7E4527C7B597CAF43183E453A9B981991E6FACB76"
    redis_connection = "redis://:signatrust-redis@signatrust-redis.signatrust-local-development.svc.cluster.local:6379"
    limits_per_minute = 100
    domain_name = "signatrust.test.osinfra.cn"
    [oidc]
    client_id = ""
    client_secret = ""
    auth_url = "https://omapi.test.osinfra.cn/oneid/oidc/authorize"
    token_url = "https://omapi.test.osinfra.cn/oneid/oidc/token"
    userinfo_url = "https://omapi.test.osinfra.cn/oneid/oidc/user"
    redirect_url = "https://127.0.0.1:8080/api/v1/users/callback"
    [sign-backend]
    type = "memory"
    [memory.kms-provider]
    type = "dummy"    
    [memory.encryption-engine]
    rotate_in_days = 90
    algorithm = "aes256gsm"
    [database]
    connection_url = "mysql://test:test@signatrust-database.signatrust-local-development.svc.cluster.local:3306/signatrust"
    max_connection = 10