apiVersion: apps/v1
kind: Deployment
metadata:
  name: signatrust-control-server
  namespace: signatrust
spec:
  replicas: 1
  selector:
    matchLabels:
      component: signatrust-control-server
  template:
    metadata:
      labels:
        component: signatrust-control-server
    spec:
      initContainers:
        - name: init-mysql
          image: busybox:1.28
          command: [ "sh", "-c", "until nslookup signatrust-database.signatrust-local-development.svc.cluster.local; do echo waiting for mysql service ; sleep 2; done;" ]
      containers:
        - image: tommylike/signatrust-control-server:f1e04f2fd37a92b04dfc9a4fd78cba1956654970
          imagePullPolicy: Always
          name: signatrust-server
          command: ["/app/control-server"]
          resources:
            requests:
              cpu: 4000m
              memory: 4000Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: RUST_LOG
              value: debug
          volumeMounts:
            - mountPath: /app/config/server.toml
              name: config-volume
              subPath: server.toml
          livenessProbe:
            httpGet:
              path: /api/health/
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health/
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: config-volume
          configMap:
            name: signatrust-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signatrust-control-admin
  namespace: signatrust
spec:
  replicas: 1
  selector:
    matchLabels:
      component: signatrust-control-admin
  template:
    metadata:
      labels:
        component: signatrust-control-admin
    spec:
      initContainers:
        - name: init-mysql
          image: busybox:1.28
          command: [ "sh", "-c", "until nslookup signatrust-database.signatrust-local-development.svc.cluster.local; do echo waiting for mysql service ; sleep 2; done;" ]
        - name: prepare-table
          image: tommylike/rust-sqlx
          env:
            - name: DATABASE_URL
              value: mysql://test:test@signatrust-database.signatrust-local-development.svc.cluster.local:3306/signatrust
          command:
            - /bin/sh
            - -c
            - |
              # TODO: Use commit it instead of latest master
              git clone https://gitee.com/openeuler/signatrust
              cd signatrust
              sqlx database create
              sqlx migrate run
      containers:
        - image: tommylike/signatrust-control-admin:f1e04f2fd37a92b04dfc9a4fd78cba1956654970
          imagePullPolicy: Always
          name: signatrust-control-admin
          command: ["/bin/sleep", "10000"]
          env:
            - name: RUST_LOG
              value: debug
          volumeMounts:
            - mountPath: /app/config/server.toml
              name: config-volume
              subPath: server.toml
      volumes:
        - name: config-volume
          configMap:
            name: signatrust-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signatrust-data-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: signatrust-data-server
  template:
    metadata:
      labels:
        component: signatrust-data-server
    spec:
      initContainers:
        - name: init-mysql
          image: busybox:1.28
          command: [ "sh", "-c", "until nslookup signatrust-database.signatrust-local-development.svc.cluster.local; do echo waiting for mysql service ; sleep 2; done;" ]
      containers:
        - image: tommylike/signatrust-data-server:f1e04f2fd37a92b04dfc9a4fd78cba1956654970
          imagePullPolicy: Always
          name: signatrust-server
          command: ["/app/data-server"]
          livenessProbe:
            exec:
              # NOTE: For production environment, we need to use grpc with client certificate,
              # for example, grpc_health_probe --addr=0.0.0.0:8088 -tls -tls-no-verify -tls-client-cert ./.data/certs/client/server.crt -tls-client-key ./.data/certs/client/server.key
              command:
              - /app/grpc_health_probe
              - --addr=0.0.0.0:8088
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            # NOTE: For production environment, we need to use grpc with client certificate,
            # for example, grpc_health_probe --addr=0.0.0.0:8088 -tls -tls-no-verify -tls-client-cert ./.data/certs/client/server.crt -tls-client-key ./.data/certs/client/server.key
            exec:
              command:
              - /app/grpc_health_probe
              - --addr=0.0.0.0:8088
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 4000m
              memory: 4000Mi
          ports:
            - containerPort: 8088
              name: http
              protocol: TCP
          env:
            - name: RUST_LOG
              value: debug
          volumeMounts:
            - mountPath: /app/config/server.toml
              name: config-volume
              subPath: server.toml
      volumes:
        - name: config-volume
          configMap:
            name: signatrust-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signatrust-database
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      component: signatrust-database
  template:
    metadata:
      labels:
        component: signatrust-database
    spec:
      containers:
        - image: mysql:8.0
          imagePullPolicy: Always
          name: signatrust-database
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 10
          resources:
            requests:
              cpu: 4000m
              memory: 4000Mi
          ports:
            - containerPort: 3306
              name: db
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              value: signatrust
            - name: MYSQL_PASSWORD
              value: test
            - name: MYSQL_USER
              value: test
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: database-volume
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: database-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signatrust-client
spec:
  replicas: 1
  selector:
    matchLabels:
      component: signatrust-client
  template:
    metadata:
      labels:
        component: signatrust-client
    spec:
      containers:
        - image: tommylike/signatrust-client:f1e04f2fd37a92b04dfc9a4fd78cba1956654970
          imagePullPolicy: Always
          name: signatrust-client
          env:
            - name: RUST_LOG
              value: debug
          resources:
            requests:
              cpu: 2000m
              memory: 2000Mi
          command:
            - /bin/sh
            - -c
            - |
              sleep 100000000
          volumeMounts:
            - mountPath: /app/config/client.toml
              name: config-volume
              subPath: client.toml
            - mountPath: /app/data/
              name: client-volume
      volumes:
        - name: config-volume
          configMap:
            name: signatrust-config
        - name: client-volume
          persistentVolumeClaim:
            claimName: client-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signatrust-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      component: signatrust-redis
  template:
    metadata:
      labels:
        component: signatrust-redis
    spec:
      containers:
        - image: redis:7.2-rc-alpine
          imagePullPolicy: Always
          name: signatrust-redis
          resources:
            requests:
              cpu: 2000m
              memory: 2000Mi
          command:
            - /bin/sh
            - -c
            - |
              /usr/local/bin/redis-server --requirepass signatrust-redis